# conda env create --name locker --file conda_env_locker.yml
name: locker
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.13
  - pip
  # Lock & Pack
  - conda-lock 
  - conda-pack
  # Required
  - numpy
  - matplotlib
  # Testing
  - pytest
  # Notebook usage
  - ipykernel 
  - nbstripout
  # - pip:
  #   - pyeas
